name: Update Pull Request branch
author: juliangruber
description: 'Update a Pull Request from its base branch'
branding:
  icon: 'git-pull-request'
  color: purple
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
